--connect odbc driver
--trace OSQL-32
osql -E -DSQLSINFEP_CLIENT11

--CARGA CLIENTE11
osql -E -DSQLSINFEP_CLIENT11 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP4.sql"
osql -E -DSQLSINFEP_CLIENT13 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP4.sql"
osql -E -DSQLSINFEP_CLIENT11 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP1.sql"
osql -E -DSQLSINFEP_CLIENT13 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP1.sql"

--CARGA CLIENTE11
osql -E -DSQLSINFEP_CLIENT13 -i "D:\DBA\SPU_INS_TDWCONTA_CargaTesteTMP.sql"


--CARGA NOTEBOOK odbcad32.exe
osql -E -DSQLSINFEP_CLIENT11 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP4.sql"
osql -E -DSQLSINFEP_ODBC11 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP4.sql"
osql -E -DSQLSINFEP_ODBC13 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP4.sql"
osql -E -DSQLSINFEP_SQLSERVER -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP4.sql"
osql -E -DSQLSINFEP_CLIENT11 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP1.sql"
osql -E -DSQLSINFEP_ODBC11 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP1.sql"
osql -E -DSQLSINFEP_ODBC13 -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP1.sql"
osql -E -DSQLSINFEP_SQLSERVER -i "C:\TEMP\SPU_INS_TDWCONTA_CargaMAXDOP1.sql"
