DECLARE @NOME NVARCHAR(50)
DECLARE @FILES NVARCHAR(50)
DECLARE @sql_string nvarchar(2000) 
DECLARE BASES_CURSOR CURSOR FOR 
SELECT NAME FROM SYS.DATABASES WHERE NAME NOT IN ('MASTER','MSDB','TEMPDB','MODEL')
OPEN BASES_CURSOR
FETCH NEXT FROM BASES_CURSOR INTO @NOME
WHILE @@FETCH_STATUS=0

BEGIN
DECLARE FILES_CURSOR CURSOR FOR 
SELECT SMF.NAME FROM SYS.MASTER_FILES SMF JOIN SYS.DATABASES SDB ON SMF.DATABASE_ID=SDB.DATABASE_ID WHERE SDB.NAME=@NOME AND SMF.TYPE_DESC='LOG' AND SDB.STATE_DESC='ONLINE'
OPEN FILES_CURSOR
FETCH NEXT FROM FILES_CURSOR INTO @FILES
WHILE @@FETCH_STATUS=0

BEGIN
SET @sql_string = 'USE ' + QUOTENAME(@NOME) + ';' + CHAR(20)
SET @sql_string = @sql_string + 'ALTER DATABASE '  + QUOTENAME(@NOME) + ' SET RECOVERY SIMPLE;' + CHAR(20)
SET @sql_string = @sql_string + 'DBCC SHRINKFILE (' + @FILES + ');' + CHAR(20)
PRINT @FILES
EXEC sp_executesql @sql_string
PRINT @sql_string
FETCH NEXT FROM FILES_CURSOR INTO @FILES
END

CLOSE FILES_CURSOR
DEALLOCATE FILES_CURSOR
FETCH NEXT FROM BASES_CURSOR INTO @NOME
END
CLOSE BASES_CURSOR
DEALLOCATE BASES_CURSOR