DECLARE @NOME NVARCHAR(50)
DECLARE BASES_CURSOR CURSOR FOR 
SELECT NAME FROM SYS.DATABASES WHERE NAME NOT IN ('MASTER','MSDB','TEMPDB','MODEL')
OPEN BASES_CURSOR
FETCH NEXT FROM BASES_CURSOR INTO @NOME
WHILE @@FETCH_STATUS=0
BEGIN
SELECT 'ALTER DATABASE ' + @NOME + ' SET COMPATIBILITY_lEVEL=110'
FETCH NEXT FROM BASES_CURSOR INTO @NOME
END
CLOSE BASES_CURSOR
DEALLOCATE BASES_CURSOR