declare @dt_base_processamento datetime = null
set @dt_base_processamento='2022-09-28'
select
			origem.DATA_IMPORTACAO_REGISTRO DATA_IMPORTACAO_REGISTRO,
			origem.cod_operacional_participante cod_operacional_participante, 
			origem.num_identificacao_conta num_identificacao_conta,
			@dt_base_processamento data_inicio_vigencia,
			null data_fim_vigencia,				
			isnull( origem.num_sequencial_conta ,0) num_sequencial_conta,
			isnull( origem.num_sequencial_entidade_participante ,0) num_sequencial_entidade_participante,
			isnull( origem.num_sequencial_entidade_investidor ,0) num_sequencial_entidade_investidor,
			isnull( origem.cod_tipo_pessoa  ,'') cod_tipo_pessoa,
			isnull( origem.num_documento_identificacao ,'') num_documento_identificacao,
			isnull( origem.num_documento_identificacao_formatado ,'') num_documento_identificacao_formatado,
			isnull( origem.nome_completo_razao_social ,'') nome_completo_razao_social,
			isnull( origem.num_sequencial_tipo_conta ,0) num_sequencial_tipo_conta,
			isnull( origem.nome_tipo_conta ,'') nome_tipo_conta,
			isnull( origem.num_sequencial_situacao ,0) num_sequencial_situacao,
			isnull( origem.nome_situacao ,'') nome_situacao,
			isnull( origem.data_situacao_atual , '1900-01-01') data_situacao_atual,
			isnull( origem.cod_motivo_situacao  ,0) cod_motivo_situacao,
			isnull( origem.nome_motivo_situacao ,'') nome_motivo_situacao,
			isnull( origem.cod_ocupacao ,'') cod_ocupacao,
			isnull( origem.ind_conta_propria_participante_negociacao ,'') ind_conta_propria_participante_negociacao,
			isnull( origem.ind_pessoa_vinculado ,'') ind_pessoa_vinculado,
			isnull( origem.num_sequencial_titular_conta_endereco ,0) num_sequencial_titular_conta_endereco,
			isnull( origem.cod_atividade_economica_primaria ,'') cod_atividade_economica_primaria,
			isnull( origem.num_sequencial_conta_master ,0) num_sequencial_conta_master,
			isnull( origem.num_identificacao_conta_master ,'') num_identificacao_conta_master,
			isnull( origem.num_sequencial_entidade_participante_master ,0) num_sequencial_entidade_participante_master,
			isnull( origem.num_sequencial_entidade_investidor_master ,0) num_sequencial_entidade_investidor_master,
			isnull( origem.cod_operacional_participante_master ,'') cod_operacional_participante_master,
			isnull( origem.num_documento_identificacao_master ,'') num_documento_identificacao_master,
			isnull( origem.num_documento_identificacao_formatado_master ,'') num_documento_identificacao_formatado_master,
			isnull( origem.nome_completo_razao_social_master ,'') nome_completo_razao_social_master,
			isnull( origem.cod_tipo_pessoa_master ,'') cod_tipo_pessoa_master,
			isnull( origem.cod_atividade_economica_primaria_master ,'') cod_atividade_economica_primaria_master,
			isnull( origem.cod_ocupacao_master  ,'') cod_ocupacao_master,
			isnull( origem.num_sequencial_situacao_master ,0) num_sequencial_situacao_master,
			isnull( origem.num_sequencial_conta_proximo_nivel ,0) num_sequencial_conta_proximo_nivel,
			isnull( origem.num_identificacao_conta_proximo_nivel ,'') num_identificacao_conta_proximo_nivel,
			isnull( origem.num_sequencial_entidade_participante_proximo_nivel ,0) num_sequencial_entidade_participante_proximo_nivel,
			isnull( origem.num_sequencial_entidade_investidor_proximo_nivel ,0) num_sequencial_entidade_investidor_proximo_nivel,
			isnull( origem.cod_operacional_participante_proximo_nivel ,'') cod_operacional_participante_proximo_nivel,
			isnull( origem.num_documento_identificacao_proximo_nivel ,'') num_documento_identificacao_proximo_nivel,
			isnull( origem.num_documento_identificacao_formatado_proximo_nivel ,'') num_documento_identificacao_formatado_proximo_nivel,
			isnull( origem.nome_completo_razao_social_proximo_nivel ,'') nome_completo_razao_social_proximo_nivel,
			isnull( origem.cod_tipo_pessoa_proximo_nivel ,'') cod_tipo_pessoa_proximo_nivel,
			isnull( origem.cod_atividade_economica_primaria_proximo_nivel ,'') cod_atividade_economica_primaria_proximo_nivel,
			isnull( origem.cod_ocupacao_proximo_nivel ,'') cod_ocupacao_proximo_nivel,
			isnull( origem.num_sequencial_situacao_proximo_nivel ,0) num_sequencial_situacao_proximo_nivel,
			isnull( origem.num_sequencial_conta_final ,0) num_sequencial_conta_final,
			isnull( origem.num_identificacao_conta_final ,'') num_identificacao_conta_final,
			isnull( origem.num_sequencial_entidade_participante_final ,0) num_sequencial_entidade_participante_final,
			isnull( origem.num_sequencial_entidade_investidor_final ,0) num_sequencial_entidade_investidor_final,
			isnull( origem.cod_operacional_participante_final ,'') cod_operacional_participante_final,
			isnull( origem.num_documento_identificacao_final ,'') num_documento_identificacao_final,
			isnull( origem.num_documento_identificacao_formatado_final ,'') num_documento_identificacao_formatado_final,
			isnull( origem.nome_completo_razao_social_final ,'') nome_completo_razao_social_final,
			isnull( origem.cod_tipo_pessoa_final ,'') cod_tipo_pessoa_final,
			isnull( origem.cod_atividade_economica_primaria_final ,'') cod_atividade_economica_primaria_final,
			isnull( origem.cod_ocupacao_final  , '') cod_ocupacao_final,
			isnull( origem.num_sequencial_situacao_final ,0) num_sequencial_situacao_final,
			isnull( origem.ind_conta_final , 0) ind_conta_final,
			isnull( origem.num_documento_identificacao_cvm , '') num_documento_identificacao_cvm,
			isnull( origem.num_documento_identificacao_cvm_proximo_nivel , '') num_documento_identificacao_cvm_proximo_nivel,
			isnull( origem.num_documento_identificacao_cvm_final , '') num_documento_identificacao_cvm_final,
			isnull( origem.dthr_inclusao,'1900-01-01') dthr_inclusao,
			isnull( origem.ind_cadastro_simplificado , '')	ind_cadastro_simplificado,
			isnull( origem.num_sequencial_titular_conta_telefone , 0) num_sequencial_titular_conta_telefone,
			isnull( origem.num_sequencial_titular_conta_email , 0) num_sequencial_titular_conta_email,
			isnull( origem.num_documento_nif,'') num_documento_nif,
			isnull( origem.num_documento_nif_proximo_nivel,'') num_documento_nif_proximo_nivel,
			isnull( origem.num_documento_nif_final,'') num_documento_nif_final,
            isnull( origem.num_sequencial_tipo_entidade_investidor,0) num_sequencial_tipo_entidade_investidor,
            isnull( origem.num_sequencial_tipo_entidade_investidor_proximo_nivel,0) num_sequencial_tipo_entidade_investidor_proximo_nivel,
            isnull( origem.num_sequencial_tipo_entidade_investidor_final,0) num_sequencial_tipo_entidade_investidor_final
			INTO #TEMP_ADWCONTA_D0
		from stg.ADWCONTA_D0 origem  (nolock) 
        where origem.DATA_IMPORTACAO_REGISTRO = @dt_base_processamento
		group by
			origem.DATA_IMPORTACAO_REGISTRO,
			origem.cod_operacional_participante, 
			origem.num_identificacao_conta ,
			isnull( origem.num_sequencial_conta ,0) ,
			isnull( origem.num_sequencial_entidade_participante ,0) ,
			isnull( origem.num_sequencial_entidade_investidor ,0) ,
			isnull( origem.cod_tipo_pessoa  ,'') ,
			isnull( origem.num_documento_identificacao ,'') ,
			isnull( origem.num_documento_identificacao_formatado ,'') ,
			isnull( origem.nome_completo_razao_social ,'') ,
			isnull( origem.num_sequencial_tipo_conta ,0) ,
			isnull( origem.nome_tipo_conta ,'') ,
			isnull( origem.num_sequencial_situacao ,0) ,
			isnull( origem.nome_situacao ,'') ,
			isnull( origem.data_situacao_atual , '1900-01-01') ,
			isnull( origem.cod_motivo_situacao  ,0) ,
			isnull( origem.nome_motivo_situacao ,'') ,
			isnull( origem.cod_ocupacao ,'') ,
			isnull( origem.ind_conta_propria_participante_negociacao ,'') ,
			isnull( origem.ind_pessoa_vinculado ,'') ,
			isnull( origem.num_sequencial_titular_conta_endereco ,0) ,
			isnull( origem.cod_atividade_economica_primaria ,'') ,
			isnull( origem.num_sequencial_conta_master ,0) ,
			isnull( origem.num_identificacao_conta_master ,'') ,
			isnull( origem.num_sequencial_entidade_participante_master ,0) ,
			isnull( origem.num_sequencial_entidade_investidor_master ,0) ,
			isnull( origem.cod_operacional_participante_master ,'') ,
			isnull( origem.num_documento_identificacao_master ,'') ,
			isnull( origem.num_documento_identificacao_formatado_master ,'') ,
			isnull( origem.nome_completo_razao_social_master ,'') ,
			isnull( origem.cod_tipo_pessoa_master ,'') ,
			isnull( origem.cod_atividade_economica_primaria_master ,'') ,
			isnull( origem.cod_ocupacao_master  ,'') ,
			isnull( origem.num_sequencial_situacao_master ,0) ,
			isnull( origem.num_sequencial_conta_proximo_nivel ,0) ,
			isnull( origem.num_identificacao_conta_proximo_nivel ,'') ,
			isnull( origem.num_sequencial_entidade_participante_proximo_nivel ,0) ,
			isnull( origem.num_sequencial_entidade_investidor_proximo_nivel ,0) ,
			isnull( origem.cod_operacional_participante_proximo_nivel ,'') ,
			isnull( origem.num_documento_identificacao_proximo_nivel ,'') ,
			isnull( origem.num_documento_identificacao_formatado_proximo_nivel ,'') ,
			isnull( origem.nome_completo_razao_social_proximo_nivel ,'') ,
			isnull( origem.cod_tipo_pessoa_proximo_nivel ,'') ,
			isnull( origem.cod_atividade_economica_primaria_proximo_nivel ,'') ,
			isnull( origem.cod_ocupacao_proximo_nivel ,'') ,
			isnull( origem.num_sequencial_situacao_proximo_nivel ,0) ,
			isnull( origem.num_sequencial_conta_final ,0) ,
			isnull( origem.num_identificacao_conta_final ,'') ,
			isnull( origem.num_sequencial_entidade_participante_final ,0) ,
			isnull( origem.num_sequencial_entidade_investidor_final ,0) ,
			isnull( origem.cod_operacional_participante_final ,'') ,
			isnull( origem.num_documento_identificacao_final ,'') ,
			isnull( origem.num_documento_identificacao_formatado_final ,'') ,
			isnull( origem.nome_completo_razao_social_final ,'') ,
			isnull( origem.cod_tipo_pessoa_final ,'') ,
			isnull( origem.cod_atividade_economica_primaria_final ,'') ,
			isnull( origem.cod_ocupacao_final  , '') ,
			isnull( origem.num_sequencial_situacao_final ,0) ,
			isnull( origem.ind_conta_final , 0) ,
			isnull( origem.num_documento_identificacao_cvm , '') ,
			isnull( origem.num_documento_identificacao_cvm_proximo_nivel , '') ,
			isnull( origem.num_documento_identificacao_cvm_final , '') ,
			isnull( origem.dthr_inclusao,'1900-01-01') ,
			isnull( origem.ind_cadastro_simplificado , '')	,
			isnull( origem.num_sequencial_titular_conta_telefone , 0) ,
			isnull( origem.num_sequencial_titular_conta_email , 0) ,
			isnull( origem.num_documento_nif,''),
			isnull( origem.num_documento_nif_proximo_nivel,''),
			isnull( origem.num_documento_nif_final,''),
            isnull( origem.num_sequencial_tipo_entidade_investidor,0),
            isnull( origem.num_sequencial_tipo_entidade_investidor_proximo_nivel,0),
            isnull( origem.num_sequencial_tipo_entidade_investidor_final,0)
		order by origem.cod_operacional_participante,
					origem.num_identificacao_conta
		


INSERT INTO stg.ADWCONTA_CONSOLIDADA_D0 
		(DATA_IMPORTACAO_REGISTRO,
			cod_operacional_participante ,
			num_identificacao_conta ,
			data_inicio_vigencia ,
			data_fim_vigencia ,
			num_sequencial_conta ,
			num_sequencial_entidade_participante ,
			num_sequencial_entidade_investidor ,
			cod_tipo_pessoa  ,
			num_documento_identificacao ,
			num_documento_identificacao_formatado ,
			nome_completo_razao_social ,
			num_sequencial_tipo_conta ,
			nome_tipo_conta ,
			num_sequencial_situacao ,
			nome_situacao ,
			data_situacao_atual ,
			cod_motivo_situacao  ,
			nome_motivo_situacao ,
			cod_ocupacao ,
			ind_conta_propria_participante_negociacao ,
			ind_pessoa_vinculado ,
			num_sequencial_titular_conta_endereco ,
			cod_atividade_economica_primaria ,
			num_sequencial_conta_master ,
			num_identificacao_conta_master ,
			num_sequencial_entidade_participante_master ,
			num_sequencial_entidade_investidor_master ,
			cod_operacional_participante_master ,
			num_documento_identificacao_master ,
			num_documento_identificacao_formatado_master ,
			nome_completo_razao_social_master ,
			cod_tipo_pessoa_master ,
			cod_atividade_economica_primaria_master ,
			cod_ocupacao_master  ,
			num_sequencial_situacao_master ,
			num_sequencial_conta_proximo_nivel ,
			num_identificacao_conta_proximo_nivel ,
			num_sequencial_entidade_participante_proximo_nivel ,
			num_sequencial_entidade_investidor_proximo_nivel ,
			cod_operacional_participante_proximo_nivel ,
			num_documento_identificacao_proximo_nivel ,
			num_documento_identificacao_formatado_proximo_nivel ,
			nome_completo_razao_social_proximo_nivel ,
			cod_tipo_pessoa_proximo_nivel ,
			cod_atividade_economica_primaria_proximo_nivel ,
			cod_ocupacao_proximo_nivel ,
			num_sequencial_situacao_proximo_nivel ,
			num_sequencial_conta_final ,
			num_identificacao_conta_final ,
			num_sequencial_entidade_participante_final ,
			num_sequencial_entidade_investidor_final ,
			cod_operacional_participante_final ,
			num_documento_identificacao_final ,
			num_documento_identificacao_formatado_final ,
			nome_completo_razao_social_final ,
			cod_tipo_pessoa_final ,
			cod_atividade_economica_primaria_final ,
			cod_ocupacao_final   ,
			num_sequencial_situacao_final ,
			ind_conta_final  ,
			num_documento_identificacao_cvm ,
			num_documento_identificacao_cvm_proximo_nivel ,
			num_documento_identificacao_cvm_final ,
			dthr_inclusao ,
			ind_cadastro_simplificado ,
			num_sequencial_titular_conta_telefone ,
			num_sequencial_titular_conta_email,
			num_documento_nif,
			num_documento_nif_proximo_nivel,
			num_documento_nif_final,
            num_sequencial_tipo_entidade_investidor,
            num_sequencial_tipo_entidade_investidor_proximo_nivel,
            num_sequencial_tipo_entidade_investidor_final
		)
SELECT * FROM #TEMP_ADWCONTA_D0

