SELECT  'GUARDAPPEVENT:START'
,'GUARDAPPEVENTTYPE:METADADO'
,'GUARDAPPEVENTSTRVALUE:METADADO';

USE ADM_BDADOS

DECLARE @PROC VARCHAR (MAX)
DECLARE @DB VARCHAR (MAX)
DECLARE @DATAINI1 DATETIME
DECLARE @DATAFIM1 DATETIME

SELECT @PROC = 'SPSF_CONSULTAR_TAREFAS_PROCESSAR',
	   @DB = 'SF',
	   @DATAINI1 = '20170620 06:00:00',
	   @DATAFIM1 = '20170620 22:00:00'

SELECT     
  CONVERT (VARCHAR(5),D.LAST_EXECUTION_TIME,114) HR_LAST_EXECUTION_TIME,
  MAX(D.AVG_ELAPSED_TIME) AVG_ELAPSED_TIME, 
  D.EXECUTION_COUNT,
  D.DATABASE_NAME BANCO,
  D.PROCEDURE_NAME,
  CONVERT(VARCHAR(8),@DATAINI1,112) TIME,
  DT_COLETA

FROM          
  TB_TIME_PROCS_DETAILS AS D WITH (NOLOCK)
WHERE      
  (D.PROCEDURE_NAME = @PROC) AND 
   D.DATABASE_NAME = @DB AND 
   (D.LAST_EXECUTION_TIME BETWEEN @DATAINI1 AND @DATAFIM1) AND
  D.PLAN_HANDLE IS NOT NULL 
GROUP BY
  CONVERT (VARCHAR(5),D.LAST_EXECUTION_TIME,114), 
  D.EXECUTION_COUNT,
  D.DATABASE_NAME,
  D.PROCEDURE_NAME,
  DT_COLETA
ORDER BY 
  D.DT_COLETA

SELECT  
  AVG(AVG_ELAPSED_TIME) AVG_ELAPSED_TIME, 
  AVG(D.EXECUTION_COUNT) AVG_EXECUTION_COUNT,
  MAX(AVG_ELAPSED_TIME) MAX_AVG_ELAPSED_TIME,
  @DATAINI1 +' - ' +@DATAFIM1 RANGE
FROM          
  TB_TIME_PROCS_DETAILS AS D WITH (NOLOCK)
WHERE      
  (D.PROCEDURE_NAME = @PROC) AND 
   D.DATABASE_NAME = @DB AND 
   (D.LAST_EXECUTION_TIME BETWEEN @DATAINI1 AND @DATAFIM1) AND
  D.PLAN_HANDLE IS NOT NULL 

/*
SELECT * FROM ADM_BDADOS.[DBO].[TB_TIME_PROCS_DETAILS] WHERE PROCEDURE_NAME = 'SPCS_CO_POSI_INVS_CUST' 
AND LAST_EXECUTION_TIME >= CONVERT(VARCHAR(20),GETDATE(),112)
*/
SELECT	'GUARDAPPEVENT:RELEASED';
GO
