USE TESOURO
GO
SELECT TOP 30
    SUBSTRING(CONVERT(VARCHAR(MAX),DS_DADOS),CHARINDEX('MS="',CONVERT(VARCHAR(MAX),DS_DADOS)) 
    + 4,CHARINDEX('/><SERVER',DS_DADOS)-CHARINDEX('MS=',DS_DADOS)-5) AS TEMPO,
   SUBSTRING(CONVERT(CHAR(19),DT_ACESSO,120),12,8) AS HORA, 
   * 
FROM  LOG_WEB_SERVICE WITH(NOLOCK) 
WHERE  1 = 1 
AND  DT_ACESSO > '2015-12-14 06:00' 
AND  DS_METODO LIKE 'CONSULTASCONSEXTRATMENSAL' 
AND CD_CONTRATO <> 0 
AND DS_LOG = 'RETORNO'
ORDER BY
CAST(SUBSTRING(CONVERT(VARCHAR(MAX),DS_DADOS),CHARINDEX('MS="',CONVERT(VARCHAR(MAX),DS_DADOS)) 
    + 4,CHARINDEX('/><SERVER',DS_DADOS)-CHARINDEX('MS=',DS_DADOS)-5) AS INT) DESC
GO    

SELECT 
AVG(CAST(SUBSTRING(CONVERT(VARCHAR(MAX),DS_DADOS),CHARINDEX('MS="',CONVERT(VARCHAR(MAX),DS_DADOS)) 
    + 4,CHARINDEX('/><SERVER',DS_DADOS)-CHARINDEX('MS=',DS_DADOS)-5) AS INT)) MEDIA
FROM  LOG_WEB_SERVICE WITH(NOLOCK) 
WHERE  1 = 1 
AND  DT_ACESSO > '2015-12-14 14:01' 
AND  DS_METODO LIKE 'CONSULTASCONSEXTRATMENSAL' 
AND CD_CONTRATO <> 0 
AND DS_LOG = 'RETORNO'

GO
SELECT 
    --CD_LOG, 
    --DS_LOG, 
    CD_CONTRATO, 
    SUBSTRING(CONVERT(CHAR(19),DT_ACESSO,120),12,8) AS HORA, 
    SUBSTRING(CONVERT(VARCHAR(MAX),DS_DADOS),CHARINDEX('MS="',CONVERT(VARCHAR(MAX),DS_DADOS)) 
    + 4,CHARINDEX('/><SERVER',DS_DADOS)-CHARINDEX('MS=',DS_DADOS)-5) AS TEMPO, 
   * 
FROM  LOG_WEB_SERVICE WITH(NOLOCK) 
WHERE  1 = 1 
AND  DT_ACESSO > '2015-12-14 06:00' 
AND  DS_METODO LIKE 'CONSULTASCONSEXTRATMENSAL' 
AND CD_CONTRATO <> 0 
AND DS_LOG = 'RETORNO'
GO    